#                                                           Developed by Sxmuray
#                                                     (Aquatic Studios @ (C) 2019-2022)

name: 'JoinGroups'
version: '1.0'
authors:
  - 'Sxmuray'
  - 'Aquatic Studios'

main: org.github.sxmuray.JoinGroups
website: https://github.com/Sxmuray/JoinGroups

softdepend:
  - PlaceholderAPI
  - Vault
  - MVdWPlaceholderAPI

description: 'All rights reserved by Aquatic Studios'

commands:
  joingroups:
    description: Command to run flight mode
    aliases: [joingroup, jp, jgroup, jgroups, jps]